//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public interface IGeneralShipController
{
	Vector3 GetTargetDisplacement ();
	Vector3 GetTargetOrientation ();	
	Vector3 GetUpVector();

	bool GetAction (ActionCode code);
	bool IsLocalPlayer();
	bool IsRemotePlayer();
}
