//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


public interface ITakeDamage
{
	void DoDamage(float number);
	void DoDamage(float number, Collision collision);

	void DoHeal(float number);
	void DoHeal(float number, Collision collision);

	void Die();


	float GetHealth();
}