//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public interface IWorldState
{
	void Create();
	void Teardown();

	void Pause();
	void Run();

	void Hide();
	void Show(bool isOverlay);

	void Update();
}