//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ScoreGUI : MonoBehaviour 
{
	string totalPower ="health 1000";
	string totalCollected = "collected 0";

	void OnGUI () 
	{
		// Make the first button. If it is pressed, Application.Loadlevel (1) will be executed
		GUI.Label (new Rect (Screen.width -100, 30, 80, 20), totalPower);		
		// Make the first button. If it is pressed, Application.Loadlevel (1) will be executed
		GUI.Label (new Rect (Screen.width -100, 50, 80 , 20), totalCollected);		
	}

	void Update()
	{
		WorldThink worldMind = null;
		if((worldMind = GetComponent<WorldThink>()) != null)
		{ //use one power for being active
//			this.totalPower = "joules "+ worldMind.totalPower.ToString();
//			this.totalCollected = "collected "+worldMind.totalCollect.ToString();
		}
	}

}
