//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class SensorHologram
{
	private GameObject detectedObject;
	private GameObject hologramObject;
	public SensorHologram (GameObject detectedObjectIn,GameObject hologramObjectIn)
	{
		detectedObject = detectedObjectIn;
		hologramObject = hologramObjectIn;
	}

	public GameObject reading
	{
		get
		{
			return detectedObject;
		}
	}
	public GameObject hologram
	{
		get
		{
			return hologramObject;
		}
	}


}

