//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using UnityEngine;

public class SpaceCell
{
	private List<GameObject> localObjects;
	private List<SpaceCell> childCells;
	private SpaceCell parent;
	private Vector3 coordMin;
	private Vector3 coordMax;
	private int isNode;

	public enum GenerationStatus {empty,generated,running};
	public SpaceCell (Vector3 coordMinIn,Vector3 coordMaxIn,SpaceCell parentIn)
	{
		isNode = 1;
		GameObject go = new GameObject ();
		coordMin = coordMinIn;
		coordMax = coordMaxIn;


		parent = parentIn;
		localObjects = new List<GameObject> ();
		//childCells = new List<SpaceCell> ();

		if(SRLConfiguration.CELL_debug == 1)
		{


		}
	}


	public void Split()
	{
		isNode = 1;

	}

	public void Load()
	{


	}
	public void Unload()
	{
		
		
	}

	public void Destroy()
	{
		
		
	}
	public void AddGameObject(GameObject obj)
	{


	}



}

