//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;


public class SRLConfiguration
{
	public const int P_mvdist = 300;
	public const int W_length = 3000;
	public const int W_width = 50;
	public const int W_height = 8;
	public const int CELL_debug = 1;
	public const int PATH_debug = 1;

	private static Hashtable settings  = new Hashtable ();
	private static SRLConfiguration instance;

	public SRLConfiguration ()
	{
		instance = new SRLConfiguration ();
		settings = new Hashtable ();
	}

//	public static void Init()
//	{
//		if(settings == null)
//			settings = new Hashtable ();
//	}

	public static string GetSetting (string key, string value = null)
	{
//		Init ();
		if (settings [key] == null)
				settings [key] = value;
			return settings[key] as string;
	}

	public static int GetSettingInt (string key, int value)
	{
//		Init ();
//		Debug.Log (settings);
		if (settings [key] == null)
			settings [key] = value;
		return System.Convert.ToInt32(settings[key]);
	}

	public static double GetSettingDouble (string key, double value)
	{
//		Init ();
		if (settings [key] == null)
			settings [key] = value;
		return System.Convert.ToDouble(settings[key]);
	}

	public static void SetSetting (string key,string val, string unsetValue)
	{
//		Init ();
		settings[key] = val;
	}




}

