//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class WorldCreate
{
	public enum WorldType : int {debug_game = 1, dev_engineTest = 2 , game = 3};

	public WorldCreate()
	{
	
	}

	private void WorldTeardown ()
	{


	}

	public void LoadWorld(WorldType world)
	{
		WorldTeardown ();
		LoadSingleCreate(world);
	}

	/*Create a simple world*/
	private bool LoadSingleCreate(WorldType world)
	{
		//	SpaceCell spaceSystem = new SpaceCell (new Vector3 (-100, -100, -100),new Vector3 (100, 100, 100), null);


		//Create a couple of objects.
		GameObject newObj;

		newObj = GameObject.Instantiate (Resources.Load ("World")) as GameObject;
		newObj.transform.position = new Vector3 (0, 0, 0);
		newObj.name = "World";


		GameObject path = new GameObject ();
		path.AddComponent<SpacePath> ();
		path.name = "SpacePath";


		newObj = GameObject.Instantiate (Resources.Load ("SpaceScene")) as GameObject;
		newObj.transform.position = new Vector3 (0, 0, 0);
		newObj.name = "SpaceScene";

		newObj = GameObject.Instantiate (Resources.Load ("DebugCursorConsole")) as GameObject;
		newObj.transform.position = new Vector3 (0, 0, 0);
		newObj.name = "DebugCursorConsole";

		newObj = GameObject.Instantiate (Resources.Load ("SystemLight")) as GameObject;
		newObj.transform.position = new Vector3 (0, 0, 0);
		newObj.name = "SystemLight";
		//path.GetComponent<SpacePath>().GetLastPoint();

		newObj = GameObject.Instantiate (Resources.Load ("Environment/WarpOrb")) as GameObject;
		newObj.transform.position = new Vector3 (4000, 0, 0);
		newObj.name = "WarpOrb";

		//Actors in the scene
		for (int i =0; i < 100; i++)
		{
			float tZ = UnityEngine.Random.Range (-150, 150);
			float tY = UnityEngine.Random.Range (-1, 1);
			float rX = UnityEngine.Random.Range (0, 360);
			float rY = UnityEngine.Random.Range (0, 360);
			float rz = UnityEngine.Random.Range (0, 360);
			float pos = UnityEngine.Random.Range (100, 4000);

		//	newObj = CompoundObjectFactory.Create("Asteroid "+i,CompoundObjectFactory.COType.Asteroid) as GameObject;
		//	newObj.transform.position = new Vector3 (pos, 4,tZ );
			//newObj.transform.rotation.eulerAngles = new Vector3(rX,rY,rz);
			newObj.transform.rotation = Quaternion.Euler(rX,rY,rz);
			 pos = UnityEngine.Random.Range (100, 4000);
			 tZ = UnityEngine.Random.Range (-150, 150);
			 tY = UnityEngine.Random.Range (-1, 1);
			newObj = CompoundObjectFactory.Create("SpaceCloudExample ",CompoundObjectFactory.COType.Cloud) as GameObject;
			newObj.transform.position = new Vector3 (pos, 4, tZ);
		}
		newObj = CompoundObjectFactory.Create("Robot",CompoundObjectFactory.COType.Player) as GameObject;
		newObj.transform.position = new Vector3 (10, 0, 0);

		if(world == WorldType.dev_engineTest)
		{
			GameObject engineTest = GameObject.Instantiate(Resources.Load("Debug/EngineTest")) as GameObject;
			engineTest.transform.parent = newObj.transform;//.transform.FindChild("Body").gameObject;
		}



		return true;
	}

}

